/*
-- Query: SELECT * FROM fog.Orderline
LIMIT 0, 1000

-- Date: 2017-05-26 10:40
*/
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne carport del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper Carport del',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'45x95 mm. ubh. Reglar',240,6,'losholter i gavle af skur',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'19x100 mm. trykimp. Braet',240,21,'til beklaedning af gavle 1 pa 2',25200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'25x50 mm. trykimp. Braet',540,2,'til montering oven pa tagfodslaegte',5400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'38x73 mm. Taglaegte T1',420,1,'toplaegte',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (14,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'25x200 mm. trykimp. Braet',360,2,'understernbraedder til for- & bagende',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'25x200 mm. trykimp. Braet',360,4,'understernbraedder til siderne',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'25x125 mm. trykimp. Braet',360,4,'oversternbraedder til siderne',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'45x95 mm. ubh. Reglar',360,6,'losholter til skur gavle',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'45x195 mm. ubh. Spaertrae',480,2,'remme i sider, sadles ned i stolper',3840);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'45x195 mm. ubh. Spaertrae',480,11,'spaer. monteres pa rem',21120);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'19x100 mm. trykimp. Braet',210,130,'til beklaedning af skur 1 pa 2',136500);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'19x100 mm. trykimp. Braet',360,4,'vandbraet pa stern i sider',7200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (15,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'25x150 mm. trykimp. Braet',480,2,'Sternbraedder til siderne carport del',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'45x195 mm. ubh. Spaertrae',480,2,'remme i sider, sadles ned i stolper Carport del',3840);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'45x95 mm. ubh. Reglar',240,12,'losholter i gavle af skur',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'19x100 mm. trykimp. Braet',240,46,'til beklaedning af gavle 1 pa 2',55200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'19x100 mm. trykimp. Braet',210,195,'til beklaedning af skur 1 pa 2',204750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'25x50 mm. trykimp. Braet',540,3,'til montering oven pa tagfodslaegte',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'38x73 mm. Taglaegte T1',420,2,'toplaegte',5040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (16,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (17,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne carport del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper Carport del',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'45x95 mm. ubh. Reglar',240,6,'losholter i gavle af skur',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'19x100 mm. trykimp. Braet',240,21,'til beklaedning af gavle 1 pa 2',25200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'25x50 mm. trykimp. Braet',540,2,'til montering oven pa tagfodslaegte',5400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'38x73 mm. Taglaegte T1',420,1,'toplaegte',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (18,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (19,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (20,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (21,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (22,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (23,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (25,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne carport del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper Carport del',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'45x95 mm. ubh. Reglar',240,6,'losholter i gavle af skur',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'19x100 mm. trykimp. Braet',240,21,'til beklaedning af gavle 1 pa 2',25200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'25x50 mm. trykimp. Braet',540,2,'til montering oven pa tagfodslaegte',5400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'38x73 mm. Taglaegte T1',420,1,'toplaegte',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (26,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (27,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (28,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne carport del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper Carport del',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'45x95 mm. ubh. Reglar',240,6,'losholter i gavle af skur',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'19x100 mm. trykimp. Braet',240,21,'til beklaedning af gavle 1 pa 2',25200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'25x50 mm. trykimp. Braet',540,2,'til montering oven pa tagfodslaegte',5400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'38x73 mm. Taglaegte T1',420,1,'toplaegte',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (29,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'25x150 mm. trykimp. Braet',480,2,'vindskeder pa rejsning',2880);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne carport del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'25x150 mm. trykimp. Braet',480,1,'Sternbraedder til siderne skur del',1440);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'faedigskaret',1,1,'byg-selv spaer (skal samles) 8 stk',4);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'97x97 mm. trykimp. Stolpe',300,9,'Stolper nedgraves 90 cm',8100);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper Carport del',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'45x95 mm. ubh. Reglar',240,4,'losholter i siderne af skur',5760);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'45x95 mm. ubh. Reglar',240,6,'losholter i gavle af skur',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'19x100 mm. trykimp. Braet',480,2,'Vand bræt pa vindskeder',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'19x100 mm. trykimp. Braet',240,21,'til beklaedning af gavle 1 pa 2',25200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'25x50 mm. trykimp. Braet',540,2,'til montering oven pa tagfodslaegte',5400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'38x73 mm. Taglaegte T1',540,1,'til z pa bagside af dor',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'38x73 mm. Taglaegte T1',540,21,'til montering pa spaer, 7 raekker laegter pa hver skiftevis 1 hel & 1 halv laegte',68040);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'38x73 mm. Taglaegte T1',420,1,'toplaegte',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'B&C Dobbelt -s sort',0,300,'monteres pa taglaegter 6 raekker af 24 sten pa hver side af taget',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'B&C Rygsten sort',0,21,'monteres pa toplaegte med medfolgende beslag. Se tagsten vejledning',105);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'B&C Toplaegte holder',0,8,'monteres pa toppen af spaeret (til toplaegte)',24);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'B&C Rygstensbeslag',0,21,'til montering af rygsten',189);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'B&C Tagstensbindere & nakkekroge',0,2,'til montering af tagsten, alle ydersten + hver anden fastgores',10);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'universal hojre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'universal venstre',190,8,'til montering af spaer pa rem',80);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'50x75 mm. Stalddorsgreb',0,1,'til las på dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'t-haengsel',390,2,'til dor i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'vinkelbeslag',35,20,'til montering af losholter i skur',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern, vindskeder, vindkryds & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'5x40 mm. beslagskruer 250 stk.',0,1,'til montering af universalbeslag & toplaegte',250);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'5x100 mm. skruer 100 stk.',0,2,'til taglaegter',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'10x120 mm. Braeddebolt',0,20,'til montering af rem pa stolper',400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'40x40 mm. firkantskiver',11,20,'til montering af rem pa stolper',4000);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'4,5x70 mm. skruer 200 stk.',0,3,'til montering af yderste braet ved beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (30,'4,5x50 mm. skruer 350 stk.',0,2,'til montering af inderste braet ved beklaedning',700);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'25x200 mm. trykimp. Braet',540,1,'understernbraedder til for- & bagende',1080);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'25x200 mm. trykimp. Braet',540,2,'understernbraedder til siderne',2160);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'25x125 mm. trykimp. Braet',360,1,'oversternbraedder til forenden',3240);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'25x125 mm. trykimp. Braet',540,2,'oversternbraedder til siderne',9720);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'38x73 mm. Laegte',420,1,'til Z pa bagside af dor',2520);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'45x95 mm. ubh. Reglar',240,6,'losholter til skur gavle',8640);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'45x95 mm. ubh. Reglar',360,8,'losholter til skur sider',17280);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'45x195 mm. ubh. Spaertrae',480,1,'remme i sider, sadles ned i stolper (skur del, deles)',1920);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'45x195 mm. ubh. Spaertrae',480,8,'spaer. monteres pa rem',15360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'97x97 mm. trykimp. Stolpe',300,11,'stolper nedgraves 90 cm. i jord',9900);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'19x100 mm. trykimp. Braet',210,97,'til beklaedning af skur 1 pa 2',101850);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'19x100 mm. trykimp. Braet',480,2,'vandbraet pa stern i sider',4800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'19x100 mm. trykimp. Braet',360,1,'vandbraet pa stern i forende',1800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'Plastmo Ecolite Blue',600,6,'tagplader monteres pa spaer',21600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'Plastmo Ecolite Blue',360,6,'tagplader monteres pa spaer',12960);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'Plastmo bundskruer 200 stk.',0,3,'skruer til tagplader',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'1x20 mm. hulband 10 mtr.',0,2,'til vindkryds pa spaer',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'universal hojre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'universal venstre',190,15,'til montering af spaer pa rem',150);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'4,5x60 mm. skruer 200 stk.',0,1,'til montering af stern & vandbraet',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'4x50 mm. beslagskruer 250 stk.',0,3,'til montering af universalbeslag & hulband',750);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'10x120 mm. Braeddebolt',0,18,'til montering af rem pa stolper',360);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'40x40 mm. firkantskiver',11,12,'til montering af rem pa stolper',2400);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'4,5x70 mm. skruer 400 stk.',0,2,'til montering af yderste beklaedning',800);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'4,5x50 mm. skruer 300 stk.',0,2,'til montering af inderste beklaedning',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'50x75 mm. Stalddorsgreb',0,1,'til las pa dor i skur',200);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'t-haengsel',390,2,'til skurdor',600);
INSERT INTO `Orderline` (`idOrder`,`partName`,`length`,`quantity`,`explanation`,`price`) VALUES (31,'vinkelbeslag',35,32,'til montering af losholter i skur',960);
